server:
  port: 8888
spring:
  profiles:
    active: subversion      
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: https://DESKTOP-GUEKIJI:446/svn/spring-cloud
          searchPaths: cloud-config-repo
          username: hbl
          password: hbl